language: clojure
install: mvn dependency:resolve
script: mvn test
cache:
  directories:
  - $HOME/.m2
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
matrix:
  allow_failures:
    - jdk: openjdk7
